### ISSUE TITLE
TODO: Get File From The Command Line

### ISSUE THREAD

**Issue by jgarte** [BonfaceKilz/gn-dataset-dump#1]
Regarding this [TODO](https://github.com/BonfaceKilz/gn-dataset-dump/blob/main/dump.lisp#L25). 

See these two resources:

If you want to do it without any external library see [uiop:command-line-arguments](https://github.com/charJe/triads/blob/master/src/command-line.lisp#L23)

There's also some libraries that vindarel mentioned here for parsing command line arguments that do a lot more:

https://github.com/LispCookbook/cl-cookbook/issues/477

I recommend contributing to the cl-cookbook if you learn new things that could be added to it.

**Comment by BonfaceKilz** [comment]
jgart ***@***.***> aliandika:

> Regarding this [TODO](https://github.com/BonfaceKilz/gn-dataset-dump/blob/main/dump.lisp#L25). 
>
> See these two resources:
>
> If you want to do it without any external library see [uiop:command-line-arguments](https://github.com/charJe/triads/blob/master/src/command-line.lisp#L23)
>
> There's also some libraries that vindarel mentioned here for parsing command line arguments that do a lot more:
>
> https://github.com/LispCookbook/cl-cookbook/issues/477
>
> I recommend contributing to the cl-cookbook if you learn something that could be added to it.
>
>

Thanks for this!

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
I'm going ahead to close this.  I introduce args here: https://github.com/BonfaceKilz/gn-dataset-dump/commit/ae2724e8da96f2306b8c8d8bc7d7a28901b0b264 and also I've got rid of the connection global variable in the first place here: https://github.com/BonfaceKilz/gn-dataset-dump/commit/c6c2f153a5e46c0fbb84ae83f259cbdab1275a58

Thanks @jgarte for creating this issue!
